function plot3d_traj(traj,colorful)
% PLOT3D_TRAJ plots single trajectory in 3D with the optional argument of 
% colorful or not (1/0);
% Example:
%
% for i = 1:length(traj), plot3d_traj(traj(i),1); end
%

% Author: Alex Liberzon
% Copyright (c) 2011, TAU
% Date: 02-Sep-2011

if nargin < 2, colorful = 1; end

hold on

colors = {'r','y','m','b','k','g','c'};
random_color = colors{randi(length(colors),1)};

jump = 5; 

if colorful
    plot3(traj.xf(2:jump:end),traj.zf(2:jump:end),traj.yf(2:jump:end),...
        'MarkerFaceColor',[.85 .85 .85],'Marker','o',...
        'MarkerEdgeColor','r',... %random_color,...
        'MarkerSize',12,...
        'UserData',traj.trajid(1));
    plot3(traj.xf(1),traj.zf(1),traj.yf(1),...
        'MarkerFaceColor','w','Marker','*',...
         'MarkerEdgeColor','r',... % random_color,...
        'MarkerSize',12);
else
    plot3(traj.xf(2:jump:end),traj.zf(2:jump:end),traj.yf(2:jump:end),...
        'MarkerFaceColor','w','Marker','o',...
        'MarkerEdgeColor',[.8,.8,.8],...
        'MarkerSize',2,...
        'LineStyle',':',...
        'UserData',traj.trajid(1));
    plot3(traj.xf(1),traj.zf(1),traj.yf(1),...
        'MarkerFaceColor','w','Marker','s',...
        'MarkerEdgeColor','k',...
        'MarkerSize',2);
end
hold off
view(3)
%%