function h = view_particles_3d(X1, Y1, Z1)
%CREATEFIGURE(X1,Y1,Z1)
%  X1:  vector of x data
%  Y1:  vector of y data
%  Z1:  vector of z data

%  Auto-generated by MATLAB on 23-Feb-2010 16:26:25

% Create figure
figure1 = figure;

% Create axes
axes('Parent',figure1);
view([-31.5 34]);
box('on');
grid('on');
hold('all');

% Create plot3
h = plot3(X1,Y1,Z1,'Marker','.','LineStyle','none');

